# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/  '),
        ),
    ]
